# Generated by Django 4.1.5 on 2023-01-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                (
                    "temperature",
                    models.DecimalField(decimal_places=1, max_digits=4, null=True),
                ),
                (
                    "thermal_sensation",
                    models.DecimalField(decimal_places=1, max_digits=4, null=True),
                ),
                ("humidity", models.CharField(max_length=200)),
                (
                    "cloud",
                    models.DecimalField(decimal_places=1, max_digits=4, null=True),
                ),
                ("uv", models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ("date", models.CharField(max_length=200)),
            ],
        ),
    ]
